// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package awskmsconnector.proxies;

public enum ENUM_MessageType
{
	RAW("1ac5a106-e551-46a5-97a8-89fc093391d1"),
	DIGEST("90d82b38-a7bf-4d96-a086-8174e0684b80");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_MessageType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
