// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package awskmsconnector.proxies;

public enum ENUM_KeySpec
{
	SYMMETRIC_DEFAULT("3792587a-1327-46cf-bcbe-cb84a7472eb7"),
	AES_128("1453e6e2-f561-4688-8395-f1d677960b0d"),
	AES_256("0d7bc785-348c-48cf-a5fa-6efa39b18b5b"),
	HMAC_224("6dad9862-ca94-4308-8c1c-96464a808c33"),
	HMAC_256("c1cbaa0d-9b51-4b93-8591-c9f81abefcde"),
	HMAC_384("be1b95fd-b219-433d-96b8-4ce500507d82"),
	HMAC_512("c79e4ef5-dabc-46b3-902c-ddf03c0ca3db"),
	RSA_2048("7e24c87f-cd40-476c-8e70-af9af7dc9610"),
	RSA_3072("be3c0104-cc44-4cf0-9802-628293c62a5b"),
	RSA_4096("a0360ba6-3df1-4d6f-acc5-e193328a100b"),
	ECC_NIST_P256("c45fb606-9f3c-467d-abff-43165738aafc"),
	ECC_NIST_P384("90d19523-69a9-4fc0-8d17-2ab415ed3ceb"),
	ECC_NIST_P521("d477b6e8-db17-4b8d-bb37-c1e5949ed833"),
	ECC_NIST_EDWARDS25519("039f6166-058c-4ed5-8857-0ffaaa43d2fb"),
	ECC_SECG_P256K1("9f6f29c5-66b9-4314-a0b7-c62f28e2abe8"),
	ML_DSA_44("66b193b9-1422-45ef-8281-1a852d91dc76"),
	ML_DSA_65("6b838b30-99ea-4875-ae24-8fdfc268f56a"),
	ML_DSA_87("f09445f9-0f1e-4e84-b868-2472ebdfb08d"),
	SM2("7ab79dc4-91e2-43b2-b315-ba5cf522cf6f");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_KeySpec(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
