// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package awskmsconnector.proxies;

public enum ENUM_KeyUsage
{
	ENCRYPT_DECRYPT("1d937bca-c9dd-4a77-a24f-70f1d956c419"),
	GENERATE_VERIFY_MAC("43e42817-9413-48f0-8bed-98f685ece55c"),
	SIGN_VERIFY("501ba53a-5754-4021-b957-e4521ac9826e"),
	KEY_AGREEMENT("85bad132-dbcd-4896-97af-b79f840bd0d2");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_KeyUsage(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
