// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package awskmsconnector.proxies;

public class KMSCredentialHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject kMSCredentialHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AWSKMSConnector.KMSCredentialHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		IsActive("IsActive"),
		AccessKeyId("AccessKeyId"),
		SecretAccessKey("SecretAccessKey"),
		Region("Region"),
		KeyId("KeyId"),
		KMSCredentialHelper_KMSCredential("AWSKMSConnector.KMSCredentialHelper_KMSCredential");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public KMSCredentialHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected KMSCredentialHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject kMSCredentialHelperMendixObject)
	{
		if (kMSCredentialHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!kMSCredentialHelperMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.kMSCredentialHelperMendixObject = kMSCredentialHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static awskmsconnector.proxies.KMSCredentialHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new awskmsconnector.proxies.KMSCredentialHelper(context, mendixObject);
	}

	public static awskmsconnector.proxies.KMSCredentialHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return awskmsconnector.proxies.KMSCredentialHelper.initialize(context, mendixObject);
	}

	/**
	 * @return value of IsActive
	 */
	public final java.lang.Boolean getIsActive()
	{
		return getIsActive(getContext());
	}

	/**
	 * @param context
	 * @return value of IsActive
	 */
	public final java.lang.Boolean getIsActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsActive.toString());
	}

	/**
	 * Set value of IsActive
	 * @param isactive
	 */
	public final void setIsActive(java.lang.Boolean isactive)
	{
		setIsActive(getContext(), isactive);
	}

	/**
	 * Set value of IsActive
	 * @param context
	 * @param isactive
	 */
	public final void setIsActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isactive)
	{
		getMendixObject().setValue(context, MemberNames.IsActive.toString(), isactive);
	}

	/**
	 * @return value of AccessKeyId
	 */
	public final java.lang.String getAccessKeyId()
	{
		return getAccessKeyId(getContext());
	}

	/**
	 * @param context
	 * @return value of AccessKeyId
	 */
	public final java.lang.String getAccessKeyId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AccessKeyId.toString());
	}

	/**
	 * Set value of AccessKeyId
	 * @param accesskeyid
	 */
	public final void setAccessKeyId(java.lang.String accesskeyid)
	{
		setAccessKeyId(getContext(), accesskeyid);
	}

	/**
	 * Set value of AccessKeyId
	 * @param context
	 * @param accesskeyid
	 */
	public final void setAccessKeyId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String accesskeyid)
	{
		getMendixObject().setValue(context, MemberNames.AccessKeyId.toString(), accesskeyid);
	}

	/**
	 * @return value of SecretAccessKey
	 */
	public final java.lang.String getSecretAccessKey()
	{
		return getSecretAccessKey(getContext());
	}

	/**
	 * @param context
	 * @return value of SecretAccessKey
	 */
	public final java.lang.String getSecretAccessKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SecretAccessKey.toString());
	}

	/**
	 * Set value of SecretAccessKey
	 * @param secretaccesskey
	 */
	public final void setSecretAccessKey(java.lang.String secretaccesskey)
	{
		setSecretAccessKey(getContext(), secretaccesskey);
	}

	/**
	 * Set value of SecretAccessKey
	 * @param context
	 * @param secretaccesskey
	 */
	public final void setSecretAccessKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String secretaccesskey)
	{
		getMendixObject().setValue(context, MemberNames.SecretAccessKey.toString(), secretaccesskey);
	}

	/**
	 * Get value of Region
	 * @param region
	 */
	public final awsauthentication.proxies.ENUM_Region getRegion()
	{
		return getRegion(getContext());
	}

	/**
	 * @param context
	 * @return value of Region
	 */
	public final awsauthentication.proxies.ENUM_Region getRegion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Region.toString());
		if (obj == null) {
			return null;
		}
		return awsauthentication.proxies.ENUM_Region.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Region
	 * @param region
	 */
	public final void setRegion(awsauthentication.proxies.ENUM_Region region)
	{
		setRegion(getContext(), region);
	}

	/**
	 * Set value of Region
	 * @param context
	 * @param region
	 */
	public final void setRegion(com.mendix.systemwideinterfaces.core.IContext context, awsauthentication.proxies.ENUM_Region region)
	{
		if (region != null) {
			getMendixObject().setValue(context, MemberNames.Region.toString(), region.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Region.toString(), null);
		}
	}

	/**
	 * @return value of KeyId
	 */
	public final java.lang.String getKeyId()
	{
		return getKeyId(getContext());
	}

	/**
	 * @param context
	 * @return value of KeyId
	 */
	public final java.lang.String getKeyId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.KeyId.toString());
	}

	/**
	 * Set value of KeyId
	 * @param keyid
	 */
	public final void setKeyId(java.lang.String keyid)
	{
		setKeyId(getContext(), keyid);
	}

	/**
	 * Set value of KeyId
	 * @param context
	 * @param keyid
	 */
	public final void setKeyId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String keyid)
	{
		getMendixObject().setValue(context, MemberNames.KeyId.toString(), keyid);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of KMSCredentialHelper_KMSCredential
	 */
	public final awskmsconnector.proxies.KMSCredential getKMSCredentialHelper_KMSCredential() throws com.mendix.core.CoreException
	{
		return getKMSCredentialHelper_KMSCredential(getContext());
	}

	/**
	 * @param context
	 * @return value of KMSCredentialHelper_KMSCredential
	 * @throws com.mendix.core.CoreException
	 */
	public final awskmsconnector.proxies.KMSCredential getKMSCredentialHelper_KMSCredential(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		awskmsconnector.proxies.KMSCredential result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.KMSCredentialHelper_KMSCredential.toString());
		if (identifier != null) {
			result = awskmsconnector.proxies.KMSCredential.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of KMSCredentialHelper_KMSCredential
	 * @param kmscredentialhelper_kmscredential
	 */
	public final void setKMSCredentialHelper_KMSCredential(awskmsconnector.proxies.KMSCredential kmscredentialhelper_kmscredential)
	{
		setKMSCredentialHelper_KMSCredential(getContext(), kmscredentialhelper_kmscredential);
	}

	/**
	 * Set value of KMSCredentialHelper_KMSCredential
	 * @param context
	 * @param kmscredentialhelper_kmscredential
	 */
	public final void setKMSCredentialHelper_KMSCredential(com.mendix.systemwideinterfaces.core.IContext context, awskmsconnector.proxies.KMSCredential kmscredentialhelper_kmscredential)
	{
		if (kmscredentialhelper_kmscredential == null) {
			getMendixObject().setValue(context, MemberNames.KMSCredentialHelper_KMSCredential.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.KMSCredentialHelper_KMSCredential.toString(), kmscredentialhelper_kmscredential.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return kMSCredentialHelperMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final awskmsconnector.proxies.KMSCredentialHelper that = (awskmsconnector.proxies.KMSCredentialHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
