// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package awskmsconnector.proxies;

public class UnitTest implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject unitTestMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AWSKMSConnector.UnitTest";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Description("Description"),
		KeySpec("KeySpec"),
		KeyUsage("KeyUsage"),
		PlainText("PlainText"),
		CipherBlob("CipherBlob"),
		KeyId("KeyId"),
		DecryptedText("DecryptedText"),
		DataKeyCipherBlob("DataKeyCipherBlob"),
		DataKeyPlainText("DataKeyPlainText");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public UnitTest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected UnitTest(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject unitTestMendixObject)
	{
		if (unitTestMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!unitTestMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.unitTestMendixObject = unitTestMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static awskmsconnector.proxies.UnitTest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new awskmsconnector.proxies.UnitTest(context, mendixObject);
	}

	public static awskmsconnector.proxies.UnitTest load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return awskmsconnector.proxies.UnitTest.initialize(context, mendixObject);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * Get value of KeySpec
	 * @param keyspec
	 */
	public final awskmsconnector.proxies.ENUM_KeySpec getKeySpec()
	{
		return getKeySpec(getContext());
	}

	/**
	 * @param context
	 * @return value of KeySpec
	 */
	public final awskmsconnector.proxies.ENUM_KeySpec getKeySpec(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.KeySpec.toString());
		if (obj == null) {
			return null;
		}
		return awskmsconnector.proxies.ENUM_KeySpec.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of KeySpec
	 * @param keyspec
	 */
	public final void setKeySpec(awskmsconnector.proxies.ENUM_KeySpec keyspec)
	{
		setKeySpec(getContext(), keyspec);
	}

	/**
	 * Set value of KeySpec
	 * @param context
	 * @param keyspec
	 */
	public final void setKeySpec(com.mendix.systemwideinterfaces.core.IContext context, awskmsconnector.proxies.ENUM_KeySpec keyspec)
	{
		if (keyspec != null) {
			getMendixObject().setValue(context, MemberNames.KeySpec.toString(), keyspec.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.KeySpec.toString(), null);
		}
	}

	/**
	 * Get value of KeyUsage
	 * @param keyusage
	 */
	public final awskmsconnector.proxies.ENUM_KeyUsage getKeyUsage()
	{
		return getKeyUsage(getContext());
	}

	/**
	 * @param context
	 * @return value of KeyUsage
	 */
	public final awskmsconnector.proxies.ENUM_KeyUsage getKeyUsage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.KeyUsage.toString());
		if (obj == null) {
			return null;
		}
		return awskmsconnector.proxies.ENUM_KeyUsage.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of KeyUsage
	 * @param keyusage
	 */
	public final void setKeyUsage(awskmsconnector.proxies.ENUM_KeyUsage keyusage)
	{
		setKeyUsage(getContext(), keyusage);
	}

	/**
	 * Set value of KeyUsage
	 * @param context
	 * @param keyusage
	 */
	public final void setKeyUsage(com.mendix.systemwideinterfaces.core.IContext context, awskmsconnector.proxies.ENUM_KeyUsage keyusage)
	{
		if (keyusage != null) {
			getMendixObject().setValue(context, MemberNames.KeyUsage.toString(), keyusage.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.KeyUsage.toString(), null);
		}
	}

	/**
	 * @return value of PlainText
	 */
	public final java.lang.String getPlainText()
	{
		return getPlainText(getContext());
	}

	/**
	 * @param context
	 * @return value of PlainText
	 */
	public final java.lang.String getPlainText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PlainText.toString());
	}

	/**
	 * Set value of PlainText
	 * @param plaintext
	 */
	public final void setPlainText(java.lang.String plaintext)
	{
		setPlainText(getContext(), plaintext);
	}

	/**
	 * Set value of PlainText
	 * @param context
	 * @param plaintext
	 */
	public final void setPlainText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String plaintext)
	{
		getMendixObject().setValue(context, MemberNames.PlainText.toString(), plaintext);
	}

	/**
	 * @return value of CipherBlob
	 */
	public final java.lang.String getCipherBlob()
	{
		return getCipherBlob(getContext());
	}

	/**
	 * @param context
	 * @return value of CipherBlob
	 */
	public final java.lang.String getCipherBlob(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CipherBlob.toString());
	}

	/**
	 * Set value of CipherBlob
	 * @param cipherblob
	 */
	public final void setCipherBlob(java.lang.String cipherblob)
	{
		setCipherBlob(getContext(), cipherblob);
	}

	/**
	 * Set value of CipherBlob
	 * @param context
	 * @param cipherblob
	 */
	public final void setCipherBlob(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cipherblob)
	{
		getMendixObject().setValue(context, MemberNames.CipherBlob.toString(), cipherblob);
	}

	/**
	 * @return value of KeyId
	 */
	public final java.lang.String getKeyId()
	{
		return getKeyId(getContext());
	}

	/**
	 * @param context
	 * @return value of KeyId
	 */
	public final java.lang.String getKeyId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.KeyId.toString());
	}

	/**
	 * Set value of KeyId
	 * @param keyid
	 */
	public final void setKeyId(java.lang.String keyid)
	{
		setKeyId(getContext(), keyid);
	}

	/**
	 * Set value of KeyId
	 * @param context
	 * @param keyid
	 */
	public final void setKeyId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String keyid)
	{
		getMendixObject().setValue(context, MemberNames.KeyId.toString(), keyid);
	}

	/**
	 * @return value of DecryptedText
	 */
	public final java.lang.String getDecryptedText()
	{
		return getDecryptedText(getContext());
	}

	/**
	 * @param context
	 * @return value of DecryptedText
	 */
	public final java.lang.String getDecryptedText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DecryptedText.toString());
	}

	/**
	 * Set value of DecryptedText
	 * @param decryptedtext
	 */
	public final void setDecryptedText(java.lang.String decryptedtext)
	{
		setDecryptedText(getContext(), decryptedtext);
	}

	/**
	 * Set value of DecryptedText
	 * @param context
	 * @param decryptedtext
	 */
	public final void setDecryptedText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String decryptedtext)
	{
		getMendixObject().setValue(context, MemberNames.DecryptedText.toString(), decryptedtext);
	}

	/**
	 * @return value of DataKeyCipherBlob
	 */
	public final java.lang.String getDataKeyCipherBlob()
	{
		return getDataKeyCipherBlob(getContext());
	}

	/**
	 * @param context
	 * @return value of DataKeyCipherBlob
	 */
	public final java.lang.String getDataKeyCipherBlob(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DataKeyCipherBlob.toString());
	}

	/**
	 * Set value of DataKeyCipherBlob
	 * @param datakeycipherblob
	 */
	public final void setDataKeyCipherBlob(java.lang.String datakeycipherblob)
	{
		setDataKeyCipherBlob(getContext(), datakeycipherblob);
	}

	/**
	 * Set value of DataKeyCipherBlob
	 * @param context
	 * @param datakeycipherblob
	 */
	public final void setDataKeyCipherBlob(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String datakeycipherblob)
	{
		getMendixObject().setValue(context, MemberNames.DataKeyCipherBlob.toString(), datakeycipherblob);
	}

	/**
	 * @return value of DataKeyPlainText
	 */
	public final java.lang.String getDataKeyPlainText()
	{
		return getDataKeyPlainText(getContext());
	}

	/**
	 * @param context
	 * @return value of DataKeyPlainText
	 */
	public final java.lang.String getDataKeyPlainText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DataKeyPlainText.toString());
	}

	/**
	 * Set value of DataKeyPlainText
	 * @param datakeyplaintext
	 */
	public final void setDataKeyPlainText(java.lang.String datakeyplaintext)
	{
		setDataKeyPlainText(getContext(), datakeyplaintext);
	}

	/**
	 * Set value of DataKeyPlainText
	 * @param context
	 * @param datakeyplaintext
	 */
	public final void setDataKeyPlainText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String datakeyplaintext)
	{
		getMendixObject().setValue(context, MemberNames.DataKeyPlainText.toString(), datakeyplaintext);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return unitTestMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final awskmsconnector.proxies.UnitTest that = (awskmsconnector.proxies.UnitTest) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
