// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package awsauthentication.proxies;

public enum ENUM_HTTPMethod
{
	GET("6f160664-ac7f-4f13-aa06-7d808901c489"),
	POST("3cd510c6-c935-42a7-a745-e5725d1b93a3"),
	PUT("af54fbb6-8c87-4333-a87c-bac671400350"),
	TRACE("3ff5f44e-c257-48a7-9a77-49f24edb4e32"),
	HEAD("c62c8900-2c8e-428d-9d95-03b538ec4738"),
	DELETE("af78f696-adaa-4032-92cc-1f564fcc5ae1"),
	CONNECT("9f97867b-0391-4da5-ab25-99c7eec55fc7"),
	OPTIONS("c2194ed9-8eaf-40fd-a36d-21391e89678e");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_HTTPMethod(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
