// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package awsauthentication.proxies;

/**
 * This enum allows for empty values to be passed into boolean fields. This in turn allows for the default configuration of those boolean values to be used
 */
public enum ENUM_Boolean
{
	_True("e80d9795-e583-4a9e-9bfb-e62c3bdcc7f8"),
	_False("79f242f9-99d4-4bf2-9124-491465a2b87f");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_Boolean(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
