// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package awsauthentication.proxies;

public enum ENUM_Region
{
	us_east_1("6aca1621-a5f4-45cb-a9d0-150029327012"),
	us_east_2("f0b4cbd1-78a9-4075-9452-952837c849b6"),
	us_west_1("5439a5fb-7088-4d09-88c4-b83dc70f9115"),
	us_west_2("c9176573-5f5b-421f-bd45-2959172a2c49"),
	af_south_1("75589338-c00f-493a-9594-6678c2656a47"),
	ap_east_1("38476fde-61f0-41b6-b698-39f8c10b41ea"),
	ap_northeast_1("afe4fc57-180b-421d-828d-c6097c3a7b63"),
	ap_northeast_2("e544d9d2-94ce-4b76-a00f-f3c6563801d2"),
	ap_northeast_3("34a2416b-91d9-4480-912b-02af55fcb0ea"),
	ap_south_1("c6431873-4876-4830-b5b3-a97658298c6a"),
	ap_south_2("e89c3bba-a5a1-4ccf-a0c2-7795f144bd5e"),
	ap_southeast_1("45daef47-c7dd-4c4a-8079-f0fcd884920b"),
	ap_southeast_2("01933990-fae9-4360-80c0-bbd5a5a23a53"),
	ap_southeast_3("c0c84e21-a787-41fc-8a27-8ba8e6793e19"),
	ap_southeast_4("72d116f6-2ea2-4b97-9f8f-1c9272cefe10"),
	ca_central_1("7090a25b-50d2-487f-b042-67c29c476db6"),
	ca_west_1("4bfa6e77-5ad5-49f8-ab29-b8efbb3ec5bd"),
	eu_central_1("e97ae558-cbf8-4f9f-be0d-ed7e69495c8e"),
	eu_central_2("7ee5a840-8b7c-4918-b905-52f942e8e227"),
	eu_north_1("2620bae0-ddc9-4e80-b8ed-00ec9a4298e5"),
	eu_south_1("0e41a5ac-0c32-4dc8-a637-37491e579147"),
	eu_south_2("e137a570-38dd-4618-afe2-dbd8b06b21a4"),
	eu_west_1("e95c572d-c590-4602-9b78-af21f38590ef"),
	eu_west_2("d1b3791d-879a-4e4b-937a-1e4f7f5082f3"),
	eu_west_3("b38140ea-c932-4a7f-bfe3-fb0633fa8b18"),
	il_central_1("4117d283-f197-449c-8cc1-2bc1854ce46b"),
	me_central_1("6ec87ec4-d440-4838-99bb-be2a65bb2d30"),
	me_south_1("4e39c899-33da-4e2f-867b-cdefe7b6cd9e"),
	mx_central_1("52929912-5434-497c-92e7-af256a6a80c6"),
	sa_east_1("db7f00b1-65d1-4489-b653-1fe7799bbdb6"),
	us_gov_east_1("82f82fda-9ef7-45bf-b103-2d267c5f8fec"),
	us_gov_west_1("42d6af5d-fca6-4326-8b02-ccd486b15b38");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_Region(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
