// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package webactions.proxies;

public enum PictureQuality
{
	original("5c3283e3-045e-4f41-ad5b-b5baeffd7b76"),
	low("34701644-2523-4bdb-846b-4e82e6110198"),
	medium("35882ae8-4d85-44c9-9882-9fff97ee2fe4"),
	high("a9194d69-cc0f-42d6-8158-d636f027421d"),
	custom("657cf352-4e43-4f50-9dbf-122807f197a1");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
