// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package encryption.proxies;

public enum CertificateType
{
	PublicKey("823d7e9e-c341-4be3-a3fe-e31acebc24f1"),
	PrivateKey("da110ecc-1e4a-4ca2-b2a6-0b88e2e8469d");

	private final java.lang.String i18nCaptionKey;
	
	private CertificateType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
