// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("327d3cb5-fbdc-466d-9b19-5981c668b5fe"),
	startsWith("5957d9ee-7aed-4d3f-a008-d280114d0705"),
	endsWith("0af1220b-a6c3-4dc0-ace5-806738d16034"),
	between("d76cd44c-553e-416d-9247-3d04c02c41c9"),
	greater("11c47026-63f3-4866-aec8-54eba0fc4ef7"),
	greaterEqual("4511092c-3ca0-400b-b83e-cd9ea112c83d"),
	equal("ba925ec3-b4ac-45dd-a340-e8ff65d60c76"),
	notEqual("82d77c3f-262d-4f26-a2ca-3b9293a60258"),
	smaller("35668a49-2690-49f5-9cc1-128a8b09021a"),
	smallerEqual("47084e90-4331-4aee-81ab-5d7aaf71bf05"),
	empty("97d01221-00fd-49b6-a5ad-79fed28d4cce"),
	notEmpty("d8008534-30c4-4823-a0b9-18f1f6bb78e9");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
