// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package awskmsconnector.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the AWSKMSConnector module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_KMS_CreateKeyBuilder(
		awskmsconnector.proxies.KMSCredentialHelper _aWSKMSCredentialHelper
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSKMSConnector.ACT_KMS_CreateKey");
		builder = builder.withParam("AWSKMSCredentialHelper", _aWSKMSCredentialHelper);
		return builder;
	}

	public static void aCT_KMS_CreateKey(
		IContext context,
		awskmsconnector.proxies.KMSCredentialHelper _aWSKMSCredentialHelper
	)
	{
		aCT_KMS_CreateKeyBuilder(
				_aWSKMSCredentialHelper
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_KMSCredentialHelper_SaveBuilder(
		awskmsconnector.proxies.KMSCredentialHelper _kMSCredentialHelper
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSKMSConnector.ACT_KMSCredentialHelper_Save");
		builder = builder.withParam("KMSCredentialHelper", _kMSCredentialHelper);
		return builder;
	}

	public static void aCT_KMSCredentialHelper_Save(
		IContext context,
		awskmsconnector.proxies.KMSCredentialHelper _kMSCredentialHelper
	)
	{
		aCT_KMSCredentialHelper_SaveBuilder(
				_kMSCredentialHelper
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder getKMSCredentialHelper_byIdBuilder(
		java.lang.String _iD
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSKMSConnector.GetKMSCredentialHelper_byId");
		builder = builder.withParam("ID", _iD);
		return builder;
	}

	public static awskmsconnector.proxies.KMSCredentialHelper getKMSCredentialHelper_byId(
		IContext context,
		java.lang.String _iD
	)
	{
		Object result = getKMSCredentialHelper_byIdBuilder(
				_iD
			)
			.execute(context);
		return result == null ? null : awskmsconnector.proxies.KMSCredentialHelper.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder getKMSCredentialId_DemoBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSKMSConnector.getKMSCredentialId_Demo");
		return builder;
	}

	public static java.lang.String getKMSCredentialId_Demo(IContext context)
	{
		Object result = getKMSCredentialId_DemoBuilder().execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder kMS_CreateKey_TestBuilder(
		awskmsconnector.proxies.UnitTest _unitTest
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSKMSConnector.KMS_CreateKey_Test");
		builder = builder.withParam("UnitTest", _unitTest);
		return builder;
	}

	public static void kMS_CreateKey_Test(
		IContext context,
		awskmsconnector.proxies.UnitTest _unitTest
	)
	{
		kMS_CreateKey_TestBuilder(
				_unitTest
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder kMS_DecryptDataKey_TestBuilder(
		awskmsconnector.proxies.UnitTest _unitTest
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSKMSConnector.KMS_DecryptDataKey_Test");
		builder = builder.withParam("UnitTest", _unitTest);
		return builder;
	}

	public static void kMS_DecryptDataKey_Test(
		IContext context,
		awskmsconnector.proxies.UnitTest _unitTest
	)
	{
		kMS_DecryptDataKey_TestBuilder(
				_unitTest
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder kMS_DecryptText_TestBuilder(
		awskmsconnector.proxies.UnitTest _unitTest
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSKMSConnector.KMS_DecryptText_Test");
		builder = builder.withParam("UnitTest", _unitTest);
		return builder;
	}

	public static void kMS_DecryptText_Test(
		IContext context,
		awskmsconnector.proxies.UnitTest _unitTest
	)
	{
		kMS_DecryptText_TestBuilder(
				_unitTest
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder kMS_EncryptText_TestBuilder(
		awskmsconnector.proxies.UnitTest _unitTest
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSKMSConnector.KMS_EncryptText_Test");
		builder = builder.withParam("UnitTest", _unitTest);
		return builder;
	}

	public static void kMS_EncryptText_Test(
		IContext context,
		awskmsconnector.proxies.UnitTest _unitTest
	)
	{
		kMS_EncryptText_TestBuilder(
				_unitTest
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder kMS_GenerateDataKey_TestBuilder(
		awskmsconnector.proxies.UnitTest _unitTest
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSKMSConnector.KMS_GenerateDataKey_Test");
		builder = builder.withParam("UnitTest", _unitTest);
		return builder;
	}

	public static void kMS_GenerateDataKey_Test(
		IContext context,
		awskmsconnector.proxies.UnitTest _unitTest
	)
	{
		kMS_GenerateDataKey_TestBuilder(
				_unitTest
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder kMSCredential_getOrCreateBuilder(
		java.lang.String _iD
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSKMSConnector.KMSCredential_getOrCreate");
		builder = builder.withParam("ID", _iD);
		return builder;
	}

	public static awskmsconnector.proxies.KMSCredential kMSCredential_getOrCreate(
		IContext context,
		java.lang.String _iD
	)
	{
		Object result = kMSCredential_getOrCreateBuilder(
				_iD
			)
			.execute(context);
		return result == null ? null : awskmsconnector.proxies.KMSCredential.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder kMSCredential_KMSCredentialHelperHelper_mapBuilder(
		awskmsconnector.proxies.KMSCredential _kMSCredential
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSKMSConnector.KMSCredential_KMSCredentialHelperHelper_map");
		builder = builder.withParam("KMSCredential", _kMSCredential);
		return builder;
	}

	public static awskmsconnector.proxies.KMSCredentialHelper kMSCredential_KMSCredentialHelperHelper_map(
		IContext context,
		awskmsconnector.proxies.KMSCredential _kMSCredential
	)
	{
		Object result = kMSCredential_KMSCredentialHelperHelper_mapBuilder(
				_kMSCredential
			)
			.execute(context);
		return result == null ? null : awskmsconnector.proxies.KMSCredentialHelper.initialize(context, (IMendixObject) result);
	}
	/**
	 * The AWS Authentication GetStaticCredentials action allows you to generate an object of type Credentials allowing for authentication using static credentials.
	 * 
	 * For testing and development purposes the static authentication should suffice, but for production environments we strongly urge you to use temporary credentials..
	 * 
	 * This action returns an object of type Credentials.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder kMSCredentialHelper_Credentials_mapBuilder(
		awskmsconnector.proxies.KMSCredentialHelper _kMSCredentialHelper
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSKMSConnector.KMSCredentialHelper_Credentials_map");
		builder = builder.withParam("KMSCredentialHelper", _kMSCredentialHelper);
		return builder;
	}

	/**
	 * The AWS Authentication GetStaticCredentials action allows you to generate an object of type Credentials allowing for authentication using static credentials.
	 * 
	 * For testing and development purposes the static authentication should suffice, but for production environments we strongly urge you to use temporary credentials..
	 * 
	 * This action returns an object of type Credentials.
	 */
	public static awsauthentication.proxies.Credentials kMSCredentialHelper_Credentials_map(
		IContext context,
		awskmsconnector.proxies.KMSCredentialHelper _kMSCredentialHelper
	)
	{
		Object result = kMSCredentialHelper_Credentials_mapBuilder(
				_kMSCredentialHelper
			)
			.execute(context);
		return result == null ? null : awsauthentication.proxies.Credentials.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder kMSCredentialHelper_decryptBuilder(
		awskmsconnector.proxies.KMSCredentialHelper _kMSCredentialHelper
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSKMSConnector.KMSCredentialHelper_decrypt");
		builder = builder.withParam("KMSCredentialHelper", _kMSCredentialHelper);
		return builder;
	}

	public static awskmsconnector.proxies.KMSCredentialHelper kMSCredentialHelper_decrypt(
		IContext context,
		awskmsconnector.proxies.KMSCredentialHelper _kMSCredentialHelper
	)
	{
		Object result = kMSCredentialHelper_decryptBuilder(
				_kMSCredentialHelper
			)
			.execute(context);
		return result == null ? null : awskmsconnector.proxies.KMSCredentialHelper.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder kMSCredentialHelper_encryptBuilder(
		awskmsconnector.proxies.KMSCredentialHelper _kMSCredentialHelper
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSKMSConnector.KMSCredentialHelper_encrypt");
		builder = builder.withParam("KMSCredentialHelper", _kMSCredentialHelper);
		return builder;
	}

	public static void kMSCredentialHelper_encrypt(
		IContext context,
		awskmsconnector.proxies.KMSCredentialHelper _kMSCredentialHelper
	)
	{
		kMSCredentialHelper_encryptBuilder(
				_kMSCredentialHelper
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder nAV_KMS_CredentialsBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSKMSConnector.NAV_KMS_Credentials");
		return builder;
	}

	public static void nAV_KMS_Credentials(IContext context)
	{
		nAV_KMS_CredentialsBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder nAV_KMS_Manager_DemoBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSKMSConnector.NAV_KMS_Manager_Demo");
		return builder;
	}

	public static void nAV_KMS_Manager_Demo(IContext context)
	{
		nAV_KMS_Manager_DemoBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder vAL_KMSCredentialHelperBuilder(
		awskmsconnector.proxies.KMSCredentialHelper _kMSCredentialHelper
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSKMSConnector.VAL_KMSCredentialHelper");
		builder = builder.withParam("KMSCredentialHelper", _kMSCredentialHelper);
		return builder;
	}

	public static boolean vAL_KMSCredentialHelper(
		IContext context,
		awskmsconnector.proxies.KMSCredentialHelper _kMSCredentialHelper
	)
	{
		Object result = vAL_KMSCredentialHelperBuilder(
				_kMSCredentialHelper
			)
			.execute(context);
		return (boolean) result;
	}
}
