// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package awskmsconnector.actions;

import awskms.KmsConnectorService;
import awskms.dto.DecryptRequest;
import awskms.dto.DecryptResponse;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

public class Decrypt extends UserAction<java.lang.String>
{
	private final java.lang.String accessKey;
	private final java.lang.String secretKey;
	private final java.lang.String region;
	private final java.lang.String keyId;
	private final java.lang.String ciphertextBlob;

	public Decrypt(
		IContext context,
		java.lang.String _accessKey,
		java.lang.String _secretKey,
		java.lang.String _region,
		java.lang.String _keyId,
		java.lang.String _ciphertextBlob
	)
	{
		super(context);
		this.accessKey = _accessKey;
		this.secretKey = _secretKey;
		this.region = _region;
		this.keyId = _keyId;
		this.ciphertextBlob = _ciphertextBlob;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		KmsConnectorService kmsService = new KmsConnectorService(accessKey, secretKey, region);
        try {
            DecryptRequest request = new DecryptRequest(keyId,ciphertextBlob);
            DecryptResponse response = kmsService.decrypt(request);
            
            if (!response.isSuccess()) {
                System.out.println("✗ Decryption failed: " + response.getErrorMessage());
                throw new com.mendix.systemwideinterfaces.MendixRuntimeException(response.getErrorMessage());
            }
            return response.getPlaintext();
        } finally {
            kmsService.close();
        }
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Decrypt";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
