// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package awskmsconnector.actions;

import awskms.KmsConnectorService;
import awskms.dto.EncryptRequest;
import awskms.dto.EncryptResponse;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

public class Encrypt extends UserAction<java.lang.String>
{
	private final java.lang.String accessKey;
	private final java.lang.String secretKey;
	private final java.lang.String region;
	private final java.lang.String keyId;
	private final java.lang.String plaintext;

	public Encrypt(
		IContext context,
		java.lang.String _accessKey,
		java.lang.String _secretKey,
		java.lang.String _region,
		java.lang.String _keyId,
		java.lang.String _plaintext
	)
	{
		super(context);
		this.accessKey = _accessKey;
		this.secretKey = _secretKey;
		this.region = _region;
		this.keyId = _keyId;
		this.plaintext = _plaintext;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		KmsConnectorService kmsService = new KmsConnectorService(accessKey, secretKey, region);
        try {
            EncryptRequest request = new EncryptRequest(keyId, plaintext);
            EncryptResponse response = kmsService.encrypt(request);
            
            if (!response.isSuccess()) {
                System.out.println("✗ Encryption failed: " + response.getErrorMessage());
                throw new com.mendix.systemwideinterfaces.MendixRuntimeException(response.getErrorMessage());
            }
            return response.getCiphertextBlob();
        } finally {
            kmsService.close();
        }
		
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Encrypt";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
