// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package awskmsconnector.actions;

import awskms.KmsConnectorService;
import awskms.dto.GenerateDataKeyRequest;
import awskms.dto.GenerateDataKeyResponse;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Returns a unique symmetric data key for use outside of AWS KMS.
 */
public class GenerateDataKey extends UserAction<java.lang.String>
{
	private final java.lang.String accessKey;
	private final java.lang.String secretKey;
	private final java.lang.String region;
	private final java.lang.String keyId;
	private final java.lang.String keySpec;

	public GenerateDataKey(
		IContext context,
		java.lang.String _accessKey,
		java.lang.String _secretKey,
		java.lang.String _region,
		java.lang.String _keyId,
		java.lang.String _keySpec
	)
	{
		super(context);
		this.accessKey = _accessKey;
		this.secretKey = _secretKey;
		this.region = _region;
		this.keyId = _keyId;
		this.keySpec = _keySpec;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		KmsConnectorService kmsService = new KmsConnectorService(accessKey, secretKey, region);
        try {
            GenerateDataKeyRequest request = new GenerateDataKeyRequest(keyId, keySpec);
            GenerateDataKeyResponse response = kmsService.generateDataKey(request);
            if (response.isSuccess()) {
               //return response.getEncryptedDataKey();
            	return response.getPlaintext();
            } else {
                System.out.println("✗ Failed to generate data key");
                System.out.println("  Error: " + response.getErrorMessage());
                throw new com.mendix.systemwideinterfaces.MendixRuntimeException(response.getErrorMessage());
            }
        } finally {
            kmsService.close();
        }
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GenerateDataKey";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
